datasource:
 driver: com.mysql.jdbc.Driver
 url: jdbc:mysql://localhost:3306/newproject
 username: root
 password: root
 dialect: org.hibernate.dialect.MySQL5Dialect

client-details:
 client-id: my-trusted-client
 secret: secret